name: Deploy to Azure Web App

on:
  push:
    branches: [ "master" ] 
  workflow_dispatch:  # Allows manual triggering

env:
  AZURE_WEBAPP_NAME: employee-wellbeing-app 
  AZURE_WEBAPP_PACKAGE_PATH: '.Backend/EmployeeWellbeingPlatform.Api'  

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore Backend/EmployeeWellbeingPlatform.Api/EmployeeWellbeingPlatform.Api.csproj
      
    - name: Build
      run: dotnet build Backend/EmployeeWellbeingPlatform.Api/EmployeeWellbeingPlatform.Api.csproj --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish Backend/EmployeeWellbeingPlatform.Api/EmployeeWellbeingPlatform.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp
